name: your_pulse_health
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #BloC
  flutter_bloc: ^7.0.1

  # Firebase
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.7.0

  cupertino_icons: ^1.0.2

  #splash screen
  animated_splash_screen: ^1.3.0

  # Page View dots indicator
  dots_indicator: ^2.0.0
#
  # Percent circle
  percent_indicator: ^3.0.1
#
  # URL launcher
  url_launcher: ^6.0.9

  # Workout Details sliding up panel
  sliding_up_panel: ^2.0.0+1

  # Video player
  video_player: ^2.1.12

  chewie: ^1.4.0
#    git:
#      url: git@github.com:v1nnk1/chewie.git
#
#
  # Countdown timer
  custom_timer: ^0.0.6

  # Image library
  image_picker: ^0.8.2

  # Reminder notification
  flutter_local_notifications: ^8.0.0

  # Native timezone
  flutter_native_timezone: ^2.0.0

  # Permission handler
  permission_handler: ^10.2.0

  #Data Base
  flutter_secure_storage: ^4.2.1

  #Osciloscopio
  oscilloscope: ^0.2.0+1

  #Heart BPM
  heart_bpm: ^1.1.1+0

  #Range dates
  syncfusion_flutter_datepicker: 20.4.44

  #syncfusion_flutter_datepicker: ^21.1.35
  intl: ^0.17.0

  #charts
  syncfusion_flutter_charts: 20.1.55

  #bluetooth
  flutter_bluetooth_serial: ^0.4.0

  #pdf
  pdf: 3.8.4
  path_provider: ^2.0.15
#  open_document: ^1.0.6+2
  open_file: ^3.3.1

  device_info_plus: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/home/
    - assets/images/exercises/
    - assets/icons/home/
    - assets/icons/workouts/
    - assets/icons/social_networks/
    - assets/videos/workouts/
    - assets/icons/pressure/
    - assets/images/tip/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
          weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
